In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [3]:
df = pd.read_csv('D:/Study/DataScience/Data/cancer.csv')

In [7]:
df.head()

FileName        Date      SegFile    b     e  LBE   LB  AC  FM  UC  \
0  Variab10.txt  01-12-1996  CTG0001.txt  240   357  120  120   0   0   0   
1    Fmcs_1.txt  03-05-1996  CTG0002.txt    5   632  132  132   4   0   4   
2    Fmcs_1.txt  03-05-1996  CTG0003.txt  177   779  133  133   2   0   5   
3    Fmcs_1.txt  03-05-1996  CTG0004.txt  411  1192  134  134   2   0   6   
4    Fmcs_1.txt  03-05-1996  CTG0005.txt  533  1147  132  132   4   0   5   

  ...   C  D  E  AD  DE  LD  FS  SUSP  CLASS  NSP  
0 ...   0  0  0   0   0   0   1     0      9    2  
1 ...   0  0  0   1   0   0   0     0      6    1  
2 ...   0  0  0   1   0   0   0     0      6    1  
3 ...   0  0  0   1   0   0   0     0      6    1  
4 ...   0  0  0   0   0   0   0     0      2    1  

[5 rows x 40 columns]

In [15]:
df = df.drop(columns= ['FileName', 'Date', 'SegFile'])

In [16]:
df.isna().sum()

b           0
e           0
LBE         0
LB          0
AC          0
FM          0
UC          0
ASTV        0
MSTV        0
ALTV        0
MLTV        0
DL          0
DS          0
DP          0
DR          0
Width       0
Min         0
Max         0
Nmax        0
Nzeros      0
Mode        0
Mean        0
Median      0
Variance    0
Tendency    0
A           0
B           0
C           0
D           0
E           0
AD          0
DE          0
LD          0
FS          0
SUSP        0
CLASS       0
NSP         0
dtype: int64

In [17]:
x = df.iloc[:, :-1].values

y = df.iloc[:, -1].values

In [18]:
x

array([[2.400e+02, 3.570e+02, 1.200e+02, ..., 1.000e+00, 0.000e+00,
        9.000e+00],
       [5.000e+00, 6.320e+02, 1.320e+02, ..., 0.000e+00, 0.000e+00,
        6.000e+00],
       [1.770e+02, 7.790e+02, 1.330e+02, ..., 0.000e+00, 0.000e+00,
        6.000e+00],
       ...,
       [1.576e+03, 2.596e+03, 1.400e+02, ..., 0.000e+00, 0.000e+00,
        5.000e+00],
       [1.576e+03, 3.049e+03, 1.400e+02, ..., 0.000e+00, 0.000e+00,
        5.000e+00],
       [2.796e+03, 3.415e+03, 1.420e+02, ..., 0.000e+00, 0.000e+00,
        1.000e+00]])

In [19]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state =0)

In [20]:
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier( n_estimators= 25, warm_start= True, bootstrap= True)

In [21]:
score = cross_val_score(rf, x, y, cv= 10)

In [23]:
print(score.mean())

0.9802210213934537


In [24]:
rf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=None, verbose=0, warm_start=True)

In [25]:
y_pred = rf.predict(x_test)

In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix

print(confusion_matrix(y_pred, y_test))

print(accuracy_score( y_test, y_pred))

[[325   7   0]
 [  1  51   0]
 [  0   0  42]]
0.9812206572769953
