In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("D:/Study/Data _Science/LinearRegression/LinearRegressionOHE.csv")

df.head()

R&D_Spend  Administration  Marketing_Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [7]:
df['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [11]:
#x = df.loc[:, df.columns != 'Profit']

#y = df.loc[:, df.columns == 'Profit']

Profit
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [13]:
dfle = df.copy()

In [17]:
dfle.State = le.fit_transform(dfle.State)

dfle

R&D_Spend  Administration  Marketing_Spend  State     Profit
0   165349.20       136897.80        471784.10      2  192261.83
1   162597.70       151377.59        443898.53      0  191792.06
2   153441.51       101145.55        407934.54      1  191050.39
3   144372.41       118671.85        383199.62      2  182901.99
4   142107.34        91391.77        366168.42      1  166187.94
5   131876.90        99814.71        362861.36      2  156991.12
6   134615.46       147198.87        278716.82      0  156122.51
7   130298.13       145530.06        323876.68      1  155752.60
8   120542.52       148718.95        311613.29      2  152211.77
9   123334.88       108679.17        304981.62      0  149759.96
10  101913.08       110594.11        229160.95      1  146121.95
11  100671.96        91790.61        249744.55      0  144259.40
12   93863.75       127320.38        249839.44      1  141585.52
13   91992.39       135495.07        252664.93      0  134307.35
14  119943.24       156547.42        256512.92      1  132602.65
15  114523.61       122616.84        261776.23      2  129917.04
16   78013.11       121597.55        264346.06      0  126992.93
17   94657.16       145077.58        282574.31      2  125370.37
18   91749.16       114175.79        294919.57      1  124266.90
19   86419.70       153514.11        273899.57      2  122776.86
20   76253.86       113867.30        298664.47      0  118474.03

In [19]:
dfle

R&D_Spend  Administration  Marketing_Spend  State     Profit
0   165349.20       136897.80        471784.10      2  192261.83
1   162597.70       151377.59        443898.53      0  191792.06
2   153441.51       101145.55        407934.54      1  191050.39
3   144372.41       118671.85        383199.62      2  182901.99
4   142107.34        91391.77        366168.42      1  166187.94
5   131876.90        99814.71        362861.36      2  156991.12
6   134615.46       147198.87        278716.82      0  156122.51
7   130298.13       145530.06        323876.68      1  155752.60
8   120542.52       148718.95        311613.29      2  152211.77
9   123334.88       108679.17        304981.62      0  149759.96
10  101913.08       110594.11        229160.95      1  146121.95
11  100671.96        91790.61        249744.55      0  144259.40
12   93863.75       127320.38        249839.44      1  141585.52
13   91992.39       135495.07        252664.93      0  134307.35
14  119943.24       156547.42        256512.92      1  132602.65
15  114523.61       122616.84        261776.23      2  129917.04
16   78013.11       121597.55        264346.06      0  126992.93
17   94657.16       145077.58        282574.31      2  125370.37
18   91749.16       114175.79        294919.57      1  124266.90
19   86419.70       153514.11        273899.57      2  122776.86
20   76253.86       113867.30        298664.47      0  118474.03

In [26]:
x = dfle.loc[:, dfle.columns != 'Profit'].values

y = dfle.loc[:, dfle.columns == 'Profit'].values

x

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 2.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 1.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 2.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 1.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 2.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 2.7871682e+05, 0.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 1.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 2.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 0.0000000e+00],
       [1.0191308e+05, 1.1059411e+05, 2.2916095e+05, 1.0000000e+00],
       [1.0067196e+05, 9.1790610e+04, 2.4974455e+05, 0.0000000e+00],
       [9.3863750e+04, 1.2732038e+05, 2.4983944e+05, 1.0000000e+00],
       [9.1992390e+04, 1.3549507e+05, 2.5266493e+05, 0.0000000e+00],
       [1.1994324e+05, 1.5654742e+

In [27]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(categorical_features= [3])

In [29]:
x = ohe.fit_transform(x).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [34]:
x = x[:, 1:]

x

array([[1.0000000e+00, 1.6534920e+05, 1.3689780e+05, 4.7178410e+05],
       [0.0000000e+00, 1.6259770e+05, 1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.5344151e+05, 1.0114555e+05, 4.0793454e+05],
       [1.0000000e+00, 1.4437241e+05, 1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.4210734e+05, 9.1391770e+04, 3.6616842e+05],
       [1.0000000e+00, 1.3187690e+05, 9.9814710e+04, 3.6286136e+05],
       [0.0000000e+00, 1.3461546e+05, 1.4719887e+05, 2.7871682e+05],
       [0.0000000e+00, 1.3029813e+05, 1.4553006e+05, 3.2387668e+05],
       [1.0000000e+00, 1.2054252e+05, 1.4871895e+05, 3.1161329e+05],
       [0.0000000e+00, 1.2333488e+05, 1.0867917e+05, 3.0498162e+05],
       [0.0000000e+00, 1.0191308e+05, 1.1059411e+05, 2.2916095e+05],
       [0.0000000e+00, 1.0067196e+05, 9.1790610e+04, 2.4974455e+05],
       [0.0000000e+00, 9.3863750e+04, 1.2732038e+05, 2.4983944e+05],
       [0.0000000e+00, 9.1992390e+04, 1.3549507e+05, 2.5266493e+05],
       [0.0000000e+00, 1.1994324e+

In [38]:
xTrain, xTest, yTrain, yTest = train_test_split(x,y, test_size = 0.3, random_state = 0)

In [39]:
linearRegressor = LinearRegression()

In [40]:
linearRegressor.fit(xTrain,yTrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [42]:
yPredict = linearRegressor.predict(xTest)

In [43]:
from sklearn.metrics import r2_score

print(r2_score(yTest,yPredict))

0.7626311627332755


# Using Imputer to fill NaN data 

In [63]:
i = pd.read_csv("D:/Study/Data _Science/LinearRegression/imputer.csv")

i.shape

(77, 4)

In [65]:
i = i.values

In [66]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values= np.nan, strategy= 'mean')

z = imputer.fit_transform(i)

array([[165349.2    , 136897.8    , 471784.1    , 192261.83   ],
       [162597.7    , 151377.59   , 443898.53   , 191792.06   ],
       [153441.51   , 101145.55   , 407934.54   , 191050.39   ],
       [144372.41   , 118671.85   , 383199.62   , 182901.99   ],
       [142107.34   ,  91391.77   , 366168.42   , 166187.94   ],
       [131876.9    ,  99814.71   , 362861.36   , 156991.12   ],
       [134615.46   , 147198.87   , 127716.82   , 156122.51   ],
       [130298.13   , 145530.06   , 323876.68   , 155752.6    ],
       [120542.52   , 148718.95   , 311613.29   , 152211.77   ],
       [123334.88   , 108679.17   , 304981.62   , 149759.96   ],
       [101913.08   , 110594.11   , 229160.95   , 146121.95   ],
       [100671.96   ,  91790.61   , 249744.55   , 144259.4    ],
       [ 93863.75   , 127320.38   , 249839.44   , 141585.52   ],
       [ 91992.39   , 135495.07   , 252664.93   , 134307.35   ],
       [119943.24   , 156547.42   , 256512.92   , 132602.65   ],
       [114523.61   , 122