In [1]:
# Impoerting Tensorflow
import tensorflow as tf

In [2]:
# Creating nodes with constants in computation graph

node1 = tf.constant(3, dtype= tf.int8)
node2 = tf.constant(5, dtype= tf.int8)

node3 = tf.add(node1, node2)

In [9]:
with tf.Session() as sess:
    print('The value of node3 is:', sess.run(node3))

The value of node3 is: 8


In [12]:
# Creating nodes in computational graph

node = tf.Variable(tf.zeros([2,2]))

Instructions for updating:
Colocations handled automatically by placer.


In [16]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    print('Tensor before addition:\n', sess.run(node))
    
    print('\n')
    node4 = node.assign( node + tf.ones([2,2]))
    
    print('Tensor after addition:\n', sess.run(node4))

Tensor before addition:
 [[0. 0.]
 [0. 0.]]


Tensor after addition:
 [[1. 1.]
 [1. 1.]]


In [18]:
# Creating Placeholders

a = tf.placeholder(tf.int32, shape= [3,1])
b = tf.placeholder(tf.int32, shape= [1,3])

c = tf.matmul(a,b)

In [19]:
# Running computational graph

with tf.Session() as sess2:
    print(sess2.run(c, feed_dict={a:[[3],[2],[1]], b:[[1,2,3]]})) 

[[3 6 9]
 [2 4 6]
 [1 2 3]]
